title: BharatBox Technical Documentation
description: Tech and Product Documentation for BharatBox
theme: just-the-docs

url: https://tech-bharatbox.github.io/technical-documentation/

color_scheme: dark

back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p"
