# Site settings
title: BharatBox Tech Documentation
email: tech@bharatbox.io
description: >- # this means to ignore newlines until "baseurl:"
 This is the Tech Documentation of the BharatBox Website and wallet integration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech-bharatbox.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
theme: minima # or any other Jekyll theme you like
plugins:
  - jekyll-feed # if you want to generate an Atom feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
